use std::net::{IpAddr, SocketAddr};

use anyhow::{Context, Result};
use hickory_net::runtime::TokioRuntimeProvider;
use hickory_resolver::config::{NameServerConfig, ResolverConfig, ResolverOpts};
use hickory_resolver::TokioResolver;
use tracing::warn;

pub(super) fn build(upstreams: &[SocketAddr]) -> Result<TokioResolver> {
    let effective = if upstreams.is_empty() {
        let parsed = parse_resolv_conf();
        if parsed.is_empty() {
            warn!("No DNS upstreams configured and /etc/resolv.conf empty; using 8.8.8.8");
            vec!["8.8.8.8:53"
                .parse()
                .context("invalid built-in DNS fallback address")?]
        } else {
            parsed
        }
    } else {
        upstreams.to_vec()
    };

    let name_servers = effective.iter().copied().map(name_server_config).collect();
    let config = ResolverConfig::from_parts(None, vec![], name_servers);
    let mut options = ResolverOpts::default();
    options.cache_size = 0;
    options.ndots = 0;

    TokioResolver::builder_with_config(config, TokioRuntimeProvider::default())
        .build()
        .map_err(|error| anyhow::anyhow!("DNS resolver build failed: {error}"))
}

fn name_server_config(address: SocketAddr) -> NameServerConfig {
    let mut config = NameServerConfig::udp(address.ip());
    for connection in &mut config.connections {
        connection.port = address.port();
    }
    config
}

fn parse_resolv_conf() -> Vec<SocketAddr> {
    std::fs::read_to_string("/etc/resolv.conf")
        .unwrap_or_default()
        .lines()
        .filter_map(|line| {
            line.trim()
                .strip_prefix("nameserver")
                .and_then(|rest| rest.trim().parse::<IpAddr>().ok())
                .map(|ip| SocketAddr::new(ip, 53))
        })
        .collect()
}

/// Parse `--dns-upstream` as comma-separated `IP[:port]` values.
pub fn parse_upstream_arg(argument: &str) -> Vec<SocketAddr> {
    if argument.is_empty() {
        return vec![];
    }
    argument
        .split(',')
        .filter_map(|part| {
            let part = part.trim();
            part.parse::<IpAddr>()
                .map(|ip| SocketAddr::new(ip, 53))
                .or_else(|_| part.parse::<SocketAddr>())
                .ok()
        })
        .collect()
}

/// Build the resolv.conf content injected into managed containers.
pub fn container_resolv_conf(gateway_ip: &str) -> String {
    format!("# Generated by outcalld -- do not edit\nnameserver {gateway_ip}\noptions ndots:0\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_upstream_addresses_and_defaults_to_port_53() {
        assert_eq!(
            parse_upstream_arg("1.1.1.1,8.8.8.8:5353,2001:db8::1,[2001:db8::2]:5353"),
            vec![
                "1.1.1.1:53".parse().unwrap(),
                "8.8.8.8:5353".parse().unwrap(),
                "[2001:db8::1]:53".parse().unwrap(),
                "[2001:db8::2]:5353".parse().unwrap(),
            ]
        );
        assert!(parse_upstream_arg("not-an-address").is_empty());
    }

    #[test]
    fn resolver_configuration_preserves_custom_port() {
        let config = name_server_config("[2001:db8::1]:5353".parse().unwrap());
        assert_eq!(config.ip, "2001:db8::1".parse::<IpAddr>().unwrap());
        assert_eq!(config.connections.len(), 1);
        assert_eq!(config.connections[0].port, 5353);
    }

    #[test]
    fn generated_resolv_conf_uses_only_managed_dns() {
        assert_eq!(
            container_resolv_conf("10.200.0.1"),
            "# Generated by outcalld -- do not edit\nnameserver 10.200.0.1\noptions ndots:0\n"
        );
    }
}
